Feat: Pendle PT Helper
InverseFinance/FiRM pull request #102
Opened 2024-12-19 18:55 UTC by 0xtj24

- Add ALE and market Pendle PT Helper
- Add custom ALE for Pendle
- Add fork tests

2025-01-01 13:48 UTC, 08xmt requested changes

2025-01-01 13:48 UTC, 08xmt commented on src/util/PendlePTHelper.sol
> +        }
Should probably fail if `ytRecipient` isn't specified. There shouldn't be a situation where YT tokens are just left in the contract.

2025-01-01 13:48 UTC, 08xmt commented on src/util/PendlePTHelper.sol
> +        }
Would be very useful if the YT could be sold for more collateral, but not sure how realistic that is.

2025-01-01 13:48 UTC, 08xmt commented on src/util/PendlePTHelper.sol
> +        (bool success, ) = router.call(callData);
I'm assuming that in cases where the ytProvider is set, the router will know how to just redeem the PT & YT for collateral, while in cases where only PT tokens are provided, it will be able to either:
1. Sell the PT for collateral if before redemption date.
2. Redeem the PT for collateral if after the redemption date.

2025-01-01 13:48 UTC, 08xmt commented on src/util/PendlePTHelper.sol
> +        if (ytProvider != address(0)) {
Should have a check and error message in case `ytProvider` doesn't have a large enough balance to supply the YT tokens.

2025-01-01 13:48 UTC, 08xmt commented on src/util/PendlePTHelper.sol
> +        if (ytProvider != address(0)) {
Thinking about it, how is the `ytProvider` supposed to work? If it's a user address or contract, that's a security vulnerability.
1. Honest user approves YT tokens as `ytProvider` for the helper contract
2. Attacker spots approve in mempool.
3. Attacker deploys PT collateral to market, then withdraws using `transformFromCollateral` with honest user as `ytProvider`

2025-01-01 13:48 UTC, 08xmt commented on src/util/PendlePTHelper.sol
> +        if (ytProvider != address(0)) {
Either only allow `ytProvider` and recipient to be same address, or only allow `ytProvider` to be `msg.sender`.

2025-01-01 13:48 UTC, 08xmt commented on src/util/PendlePTHelper.sol
> +        }
Same security problem as previously mentioned

2025-01-01 13:48 UTC, 08xmt commented on test/util/aleTests/ALEPendlePTUSDe.t.sol
> +    bytes pendleDataInitial =
MY EYES
![image](https://github.com/user-attachments/assets/fedce57a-ce53-4494-a704-cf92a90f48a2)

2025-01-01 13:48 UTC, 08xmt commented on test/util/aleTests/ALEPendlePTUSDe.t.sol
> +    bytes pendleDataInitial =
I will just assume this is good and correct

2025-01-03 00:29 UTC, 0xtj24 commented on src/util/PendlePTHelper.sol
> +        if (ytProvider != address(0)) {
Totally right, we should use `msg.sender`, which is fine for direct interaction but in the case of the ALE we would have to pass another param (`_user`) from the ALE which is the actual `msg.sender`, so for this we would need to deploy an ALE instance for Pendle markets which pass `_user` into the helper and ofc limiting only the ALE to use that function.
At this point we could do the same when minting PT and YT, sending any YT to either `_user` or `msg.sender` depending if it’s via ALE or direct interaction with the helper, so we avoid the possibility of YT tokens left in the helper (related to the previous review comment).

So basically:
- Adapt ALE to pass `_user` into helper call
- Use `_user` or `msg.sender` as YT provider/receiver, limiting functions with `_user` as param to the ALE only.

 Unless you have any better suggestion to avoid a separate ALE for Pendle markets

2025-01-03 00:43 UTC, 0xtj24 commented on src/util/PendlePTHelper.sol
> +        (bool success, ) = router.call(callData);
The PT tokens can be sold Only before maturity so when requesting the `callData` from Pendle API if it’s after maturity the swap option won’t be available, only redemptions will return a valid `callData`.
Actually after maturity the YT is not needed so I’ll fix it together with the other one to check for maturity and just using PT

2025-01-10 15:49 UTC, 0xtj24 commented on src/util/PendlePTHelper.sol
> +        if (ytProvider != address(0)) {
Fixed in [419181f](https://github.com/InverseFinance/FiRM/pull/102/commits/419181fd82b478aaad2453a218e175544b31be1c) and following

2025-01-10 15:49 UTC, 0xtj24 commented on src/util/PendlePTHelper.sol
> +        }
Fixed in [419181f](https://github.com/InverseFinance/FiRM/pull/102/commits/419181fd82b478aaad2453a218e175544b31be1c) and following

2025-01-10 15:51 UTC, 0xtj24 commented on src/util/PendlePTHelper.sol
> +        (bool success, ) = router.call(callData);
Fixed in [419181f](https://github.com/InverseFinance/FiRM/pull/102/commits/419181fd82b478aaad2453a218e175544b31be1c) and following

2025-01-10 15:51 UTC, 0xtj24 commented on src/util/PendlePTHelper.sol
> +        }
Fixed in [419181f](https://github.com/InverseFinance/FiRM/pull/102/commits/419181fd82b478aaad2453a218e175544b31be1c) and following

2025-01-13 13:11 UTC, 08xmt commented on src/util/ALEPendle.sol
> +    IERC3156FlashLender public constant flash =
Not sure if this should be setable or remain constant.

2025-01-13 13:11 UTC, 08xmt commented on src/util/ALEPendle.sol
> +    }
This modifier is no longer required with the new flashminter, right?

2025-01-13 13:11 UTC, 08xmt commented on src/util/ALEPendle.sol
> +    }
This doesn't have to be an internal function. More readable to write `dola.approve(spender, value)` than calling an internal function to do so.

2025-01-13 13:11 UTC, 08xmt commented on src/util/ALEPendle.sol
> +        _approveDola(address(flash), type(uint).max);
```suggestion
        dola.approve(address(flash), type(uint).max);
```

2025-01-13 13:11 UTC, 08xmt commented on src/util/ALEPendle.sol
> +        }
Nit: Avoid unnecessary indentation
```suggestion
        if (_helper == address(0) &&
        _buySellToken != IMarket(_market).collateral()) {
              revert MarketSetupFailed(
                  _market,
                  _buySellToken,
                  IMarket(_market).collateral(),
                  _helper
              );
        }
```

2025-01-13 13:11 UTC, 08xmt commented on src/util/ALEPendle.sol
> +        if (_helper != address(0)) {
Will there ever be pendle markets added where there won't be a helper?

2025-01-13 13:11 UTC, 08xmt commented on src/util/ALEPendle.sol
> +        bytes memory data = abi.encode(
Might save some gas on using `abi.encodePacked`. Might even be worth it to have a helper function that does all of the packing so all the encoding can be done off-chain and only the unpacking needs to be done on-chain.

2025-01-13 13:11 UTC, 08xmt commented on src/util/ALEPendle.sol
> +        if (_dbrData.amountIn != 0)
Make sure that if there's any dbr data that points to the user wanting dbr, the _buyDbr function is called.
```suggestion
        if (_dbrData.amountIn > 0 || _dbrData.minOut > 0)
```

2025-01-13 13:11 UTC, 08xmt commented on src/util/ALEPendle.sol
> +        }
Nit: Checking for 0 barely saves any gas and makes the code less readable imo.
```suggestion
        uint256 dolaToBorrow = _value + _dbrData.dola + _dbrData.amountIn;
```

2025-01-13 13:11 UTC, 08xmt commented on src/util/ALEPendle.sol
> +            );
Is this a necessary check?

2025-01-13 13:11 UTC, 08xmt commented on src/util/ALEPendle.sol
> +        }
Brevity
```suggestion
        if (_dbrData.dola != 0) {
            dola.transferFrom(_user, address(this), _dbrData.dola);
            _value + _dbrData.dola;
        }
        _approveDola(address(market), _value);
        market.repay(_user, _value);
```

2025-01-13 13:11 UTC, 08xmt commented on src/util/ALEPendle.sol
> +    function deleveragePosition(
The `leveragePosition` and `deleveragePosition` are almost the same function. If data was fed as a calldata parameter they would be the same function. Probably best to just roll them into one.

2025-01-13 13:11 UTC, 08xmt commented on src/util/ALEPendle.sol
> +            }
In what situations should there be collateral leftover, and how often will that leftover collateral be worth the gas cost to transfer it back to the receiver?

2025-01-13 13:11 UTC, 08xmt commented on src/util/ALEPendle.sol
> +            revert WithdrawFailed(assetAmount, actualAssetAmount);
Is there a reason we can't trust the amount returned by the helper?

2025-01-13 13:11 UTC, 08xmt commented on src/util/ALEPendle.sol
> +            revert DepositFailed(collateralAmount, actualCollateralAmount);
```suggestion
        uint256 actualCollateralAmount = markets[_market].collateral.balanceOf(
            address(this)
        );
        if (actualCollateralAmount < collateralAmount)
            revert DepositFailed(collateralAmount, actualCollateralAmount);
```
Is there a reason we can't trust the amount returned by the helper, and if so, can't we just return the collateral balance?

2025-01-13 13:11 UTC, 08xmt commented on src/util/PendlePTHelper.sol
> +    function getSelector(bytes memory _bytes) internal pure returns (bytes4) {
I don't understand what this function is doing.

2025-01-15 15:15 UTC, 0xtj24 commented on src/util/ALEPendle.sol
> +    }
Fixed in [713b3e4](https://github.com/InverseFinance/FiRM/pull/102/commits/713b3e442a21ede20af90cb75d1bc2ef49a28e82)

2025-01-15 15:15 UTC, 0xtj24 commented on src/util/ALEPendle.sol
> +    }
Fixed in [713b3e4](https://github.com/InverseFinance/FiRM/pull/102/commits/713b3e442a21ede20af90cb75d1bc2ef49a28e82)

2025-01-15 15:15 UTC, 0xtj24 commented on src/util/ALEPendle.sol
> +        _approveDola(address(flash), type(uint).max);
Fixed in [713b3e4](https://github.com/InverseFinance/FiRM/pull/102/commits/713b3e442a21ede20af90cb75d1bc2ef49a28e82)

2025-01-15 15:15 UTC, 0xtj24 commented on src/util/ALEPendle.sol
> +        }
Fixed in [713b3e4](https://github.com/InverseFinance/FiRM/pull/102/commits/713b3e442a21ede20af90cb75d1bc2ef49a28e82)

2025-01-15 15:16 UTC, 0xtj24 commented on src/util/ALEPendle.sol
> +        }
Fixed in [713b3e4](https://github.com/InverseFinance/FiRM/pull/102/commits/713b3e442a21ede20af90cb75d1bc2ef49a28e82)

2025-01-15 17:44 UTC, 0xtj24 commented on src/util/ALEPendle.sol
> +        }
Fixed in [e8611f5](https://github.com/InverseFinance/FiRM/pull/102/commits/e8611f54da2e64d920168ede36806a5c3622df64)

2025-01-20 14:11 UTC, 0xtj24 commented on src/util/ALEPendle.sol
> +        if (_dbrData.amountIn != 0)
if only `minOut` is set but `amountIn` is zero `buyDBR` won't do anything, but what we could do is to make this check inclusive with `&&` so only if a `minOut` is set there will be a buy, at least we avoid a sandwich

2025-01-20 14:26 UTC, 0xtj24 commented on src/util/ALEPendle.sol
> +        if (_helper != address(0)) {
Fixed in [1d87b03](https://github.com/InverseFinance/FiRM/pull/102/commits/1d87b03730125558de481d19b3bd46aac1c0e7b6)

2025-01-20 14:26 UTC, 0xtj24 commented on src/util/ALEPendle.sol
> +        if (_dbrData.amountIn != 0)
Fixed in [1d87b03](https://github.com/InverseFinance/FiRM/pull/102/commits/1d87b03730125558de481d19b3bd46aac1c0e7b6)

2025-01-20 14:29 UTC, 0xtj24 commented on src/util/ALEPendle.sol
> +    IERC3156FlashLender public constant flash =
Could probably remain constant, if we were going to upgrade the actual flash minter, the ALE would also possibly require some adjustment too so we will end up deploying a new version, and by being constant we can save some gas

2025-01-20 14:30 UTC, 0xtj24 commented on src/util/ALEPendle.sol
> +        bytes memory data = abi.encode(
Left unchanged after internal discussion and analysis

2025-01-20 14:30 UTC, 0xtj24 commented on src/util/ALEPendle.sol
> +            );
Left unchanged after internal discussion and analysis

2025-01-20 14:30 UTC, 0xtj24 commented on src/util/ALEPendle.sol
> +    function deleveragePosition(
Left unchanged after internal discussion and analysis

2025-01-20 14:30 UTC, 0xtj24 commented on src/util/ALEPendle.sol
> +            }
Left unchanged after internal discussion and analysis

2025-01-20 14:31 UTC, 0xtj24 commented on src/util/ALEPendle.sol
> +            revert WithdrawFailed(assetAmount, actualAssetAmount);
Left unchanged after internal discussion and analysis

2025-01-20 14:31 UTC, 0xtj24 commented on src/util/ALEPendle.sol
> +            revert DepositFailed(collateralAmount, actualCollateralAmount);
Left unchanged after internal discussion and analysis

2025-01-20 14:41 UTC, 08xmt commented on src/util/ALEPendle.sol
> +            _helper == address(0) &&
Should we always just revert if `_helper == address(0)`?

2025-01-20 14:42 UTC, 08xmt commented on src/util/ALEPendle.sol
> +        if (_dbrData.amountIn != 0)
> if only `minOut` is set but `amountIn` is zero `buyDBR` won't do anything, but what we could do is to make this check inclusive with `&&` so only if a `minOut` is set there will be a buy, at least we avoid a sandwich

Yeah good point.

2025-01-20 14:45 UTC, 08xmt approved these changes

2025-01-20 16:34 UTC, 0xtj24 commented on src/util/ALEPendle.sol
> +            _helper == address(0) &&
Fixed in [3cc6e03](https://github.com/InverseFinance/FiRM/pull/102/commits/3cc6e034f7263da8e2eb05aad49fdf2834667239)

2025-01-27 20:23 UTC, wavey0x commented
Mismatching logic. 

In `setMarket`, a valid helper is required.
https://github.com/InverseFinance/FiRM/blob/3cc6e034f7263da8e2eb05aad49fdf2834667239/src/util/ALEPendle.sol#L183

But that helper can be cleared to 0x0, as a valid helper is not required during `updateMarketHelper`
https://github.com/InverseFinance/FiRM/blob/3cc6e034f7263da8e2eb05aad49fdf2834667239/src/util/ALEPendle.sol#L229

2025-01-27 20:39 UTC, wavey0x commented
optional:
might consider importing the [source library](https://github.com/GNSPS/solidity-bytes-utils/blob/master/contracts/BytesLib.sol#L228) rather than a [modified copy/paste](https://github.com/InverseFinance/FiRM/blob/3cc6e034f7263da8e2eb05aad49fdf2834667239/src/util/PendlePTHelper.sol#L376).

this method should not increase your contract's bytecode size as the library's functions are internal, and the compiler will exclude any bytecode from unused functions.

2025-05-06 17:05 UTC, merged